### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by manzanit0** [Manzanit0/spidey#3]
Dealing with timeouts:

```
[error] Task #PID<0.1773.0> started from #PID<0.570.0> terminating
** (stop) exited in: :gen_server.call(:crawler_pool, {:checkout, #Reference<0.3713136520.3017539591.157568>, true}, 60000)
    ** (EXIT) time out
    (stdlib) gen_server.erl:223: :gen_server.call/3
    (poolboy) /Users/manzanit0/repositories/cookbook/deps/poolboy/src/poolboy.erl:63: :poolboy.checkout/3
    (poolboy) /Users/manzanit0/repositories/cookbook/deps/poolboy/src/poolboy.erl:82: :poolboy.transaction/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<2.126811178/0 in Spidey.Crawler.run_in_pool/3>
    Args: []
```

This was triggered when attempting to crawl: https://www.vietworldkitchen.com/blog/2021/02/deliciously-not-deep-fried-salt-and-pepper-ribs-recipe-video.html

**Comment by manzanit0** [comment]
Addressed in: https://github.com/Manzanit0/spidey/commit/2d6b9c352441519e507d0f45898506fd8dcf1903
